### ISSUE TITLE
Security Proofs

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/bertie#15]
The goal is to prove handshake security properties for the code derived from TLS 1.3.
In particular, we will prove server authentication and session key secrecy.

- [x] Generated model + *small* handwritten supplemental model should typecheck
- [x] Minimize the number of functions that must be modeled by hand, goal: ~**20** (current: 57)
- [x] #100
- [x] #104
~-  #105~
~-  [ProVerif] Incorporate code changes from #112 into ProVerif model~

**Comment by jschneider-bensch** [comment]
Moved the maintenance related task out of here.
