### ISSUE TITLE
[Feature request] Support ciphersuite / algorithms argument for `simple_https_server`

### ISSUE THREAD

**Issue by jschneider-bensch** [cryspen/bertie#66]
**Is your feature request related to a problem? Please describe.**

Currently, the `simple_https_server` is hardcoded to use `SHA256_Chacha20Poly1305_EcdsaSecp256r1Sha256_X25519` as the ciphersuite with a hardcoded certificate and key. This doesn't allow testing any of the other mandatory ciphersuites, e.g. in the self test or other interoperability tests.

**Describe the solution you'd like**

I think the simplest solution would be to give additional arguments to the library function `tls13server`  which specify a ciphersuite to use and also give a matching certificate and key.
The executable could take these as additional arguments as well and load cert + key from asset files.

**Comment by franziskuskiefer** [comment]
@jallmann did you start looking at something related to this already? Just making sure we don't do things twice or create conflicts.

**Comment by jallmann** [comment]
No, I haven't done anything in that direction yet.
