### ISSUE TITLE
Lax typecheck

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/bertie#86]
- [x] add an option to the driver for extracting the target
- [ ] add lax typechecking to CI
- [ ] Lax:
  - [x] ghost traits for `Index` (https://github.com/hacspec/hax/issues/544): **this is due for today (MARCH 4)**;
  - [x] question marks
  - [ ] IndexMut
  - [ ] Un-monomorphize UpdateAt when not slice or array
  - [ ] no implementation utils (fsti only)
  - [ ] Fix F* cast TC
  - [ ] Insert `rec` flags for simple non-mutual rec function in F* backend
  - [ ] bug monad in handsjake

**Comment by franziskuskiefer** [comment]
* how to handle "in range" for `Index` and `IndexMut`
* how to restrict `IndexMut` (we only want assignment)
* question marks

**Comment by W95Psp** [comment]
Requires [#529](https://github.com/hacspec/hax/issues/529)

**Comment by W95Psp** [comment]
Related to #545

**Comment by W95Psp** [comment]
- let rec
 - migrate update_at to Rust
 - Wrap `?`-arms in functions and promotes pure arms to Ok (rust side)
